name = "ubereats-monitor-api"
main = "cloudflare/worker.js"
compatibility_date = "2024-04-01"

# 綁定 Cloudflare D1 資料庫
[[d1_databases]]
binding = "DB"
database_name = "ubereats_monitor"
database_id = "fa6a47a1-8d29-4b68-b76f-0043c7fe352b"
